spring:
  application:
    name: order-service
  datasource:
    username: root
    password: root
    url: "jdbc:mysql://localhost:3306/order_db"
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.package: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        delivery.timeout.ms: 30000
        #thoi gian doi phan hoi tu Broker cho 1 request don le
        #default 30k
        request.timeout.ms: 15000
        #thoi gian toi da de gom lai roi gom lai (batch) truoc khi send
        #neu muon gui di ngay lap tuc thi set = 0
      acks: all #0 #1
  jpa:
    database: mysql
    show-sql: true
server:
  port: 8052